---
- name: check if sp-key.pem exists
  stat:
    path: /etc/shibboleth/sp-key.pem
  register: sp_key

- name: check if sp-cert.pem exists
  stat:
    path: /etc/shibboleth/sp-cert.pem
  register: sp_cert

- include: selfsigned.yml
  when: "(not sp_key.stat.exists) or (not sp_cert.stat.exists)"

- name: check if idp-metadata.xml exists
  stat:
    path: /secrets/idp-metadata.xml

- name: Configuring attribute-map.xml
  template: 
    src: attribute-map.xml
    dest: /etc/shibboleth/attribute-map.xml
    group: _shibd
    owner: _shibd
    mode: 0644
  
- name: Configuring shibboleth2.xml
  template: 
    src: shibboleth2.xml
    dest: /etc/shibboleth/shibboleth2.xml
    group: _shibd
    owner: _shibd
    mode: 0644
  notify: restart shibd  