---
- name: Create /etc/apache2/ssl directory
  file: 
    path: /etc/apache2/ssl
    state: directory

- name: check if ssl.crt exist
  stat:
    path: /etc/apache2/ssl/ssl.crt
  register: ssl_crt

- name: check if ssl.key exist
  stat:
    path: /etc/apache2/ssl/ssl.key
  register: ssl_key

- include: selfsigned.yml
  when: "(not ssl_crt.stat.exists) or (not ssl_key.stat.exists)"

- name: Configure apache proxy
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
  notify: restart apache
